spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: 1111
    security:
        successHandler: com.example.MyAuthenticationSuccessHandler
  flyway:
    locations: classpath:db/migration
    scripts-encoding: UTF-8
    placeholder-replacement: true
    placeholders:
      placeholder-prefix: #
        placeholder-suffix: #
